spring:
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
            - localhost:9092
      bindings:
        handleBookEvent-in-0:
          binder: kafka
          destination: BOOK_EVENT_TOPIC
          group: b
          consumer:
            partitioned: true

server:
  port: 8888