spring:
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
            - localhost:9092
      bindings:
        book-event-producer:
          binder: kafka
          destination: BOOK_EVENT_TOPIC
          content-type: application/json
      source: book-event-producer
